pkgdatadir = ${HOME}/.usr/local/share/upmpdcli
pidfile = /run/user/${UID}/upmpdcli/upmpdcli.pid
iconpath = ${HOME}/.usr/local/share/upmpdcli/icon.png
cachedir = ${HOME}/.cache/upmpdcli
presentationhtml = $HOME/.usr/local/share/upmpdcli/presentation.html

friendlyname = ${HOST} (OpenHome)
avfriendlyname = ${HOST}
ohproductroom = ${HOST} (OpenHome)
msfriendlyname = ${HOST}
upnpav = 0
openhome = 1
