pkgdatadir = /home/szymon/.usr/local/share/upmpdcli
pidfile = /run/user/1000/upmpdcli/upmpdcli.pid
iconpath = /home/szymon/.usr/local/share/upmpdcli/icon.png
cachedir = /home/szymon/.cache/upmpdcli
presentationhtml = /home/szymon/.usr/local/share/upmpdcli/presentation.html

upnpip = 192.168.1.33
friendlyname = UpMpdCli (OpenHome)
avfriendlyname = UpMpdCli
ohproductroom = UpMpdCli (OpenHome)
msfriendlyname = UpMpdCli
upnpav = 1
openhome = 1

subsonicautostart = 1
subsonicbaseurl = https://navidrome.at.home
subsonicport = 443
subsonicuser = admin
subsonicpassword = admin
subsonicserversidescrobbling = 1
