# [General]
wallpaper_dir = /home/shyman/Pictures/Wallpapers
rotation_interval = 3600
randomize = true
# available backends: auto, swaybg, hyprpaper, kde
# auto selects kde when XDG_CURRENT_DESKTOP contains 'KDE', otherwise swaybg
backend = swaybg

# [swaybg settings]
# available modes: fill, fit, stretch, center, tile
swaybg_mode = fill
# Select an output to configure. Subsequent appearance options will only apply to this output. The special value * selects all outputs.
swaybg_output = *

# [hyprpaper settings]
# available modes: cover, contain, tile
hyprpaper_mode = cover
# Example: DP-1 or all
monitor_name = 

# [pywal settings]
pywal_enabled = false
pywal_command = wal --cols16 -n
